language: php
sudo: false
matrix:
  include:
    - php: 5.3
      env: DISABLE_TLS="yes"
    - php: 5.4
      env: DISABLE_TLS="no"
    - php: 5.5
      env: DISABLE_TLS="no"
    - php: 5.6
      env: DISABLE_TLS="no"
    - php: 7.0
      env: DISABLE_TLS="no"
    - php: 7.1
      env: DISABLE_TLS="no"
    - php: hhvm
      env: DISABLE_TLS="no"
  allow_failures:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: hhvm

before_script:
  - if [ "$DISABLE_TLS" == "yes" ]; then composer config disable-tls true; fi

script:
  - composer ci

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; the php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi;'

# vim: noet ts=2 sw=2 ft=yaml nospell:
